// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionContextNode } from "./ActionContextNode";

export type ActionContextSnapshot = { window_id: string, focused_context_id: string | null, nodes: Array<ActionContextNode>, };
