// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionId } from "./ActionId";

export type ActionDescriptor = { id: ActionId, label_key: string, category: string, default_context: string, allows_keybinding: boolean, requires_project: boolean, };
