// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionId } from "./ActionId";
import type { KeyStroke } from "./KeyStroke";

/**
 * Whether an action applies to a given context snapshot, and the shortcut that
 * would trigger it there (the most specific effective binding whose context
 * matches). Drives the command palette and shortcut labels.
 */
export type ActionAvailability = { id: ActionId, available: boolean, shortcut: Array<KeyStroke> | null, };
