// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyStroke } from "../../../../src/bindings/KeyStroke";
import type { ActionInvocation } from "./ActionInvocation";

export type ActionResolution = { "status": "noMatch" } | { "status": "pendingSequence", sequence: Array<KeyStroke>, fallback: ActionInvocation | null, timeout_ms: number, } | { "status": "matched", invocation: ActionInvocation, } | { "status": "cancelled" };
