// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ActionContextNode = { id: string, parent_id: string | null, contexts: Array<string>, attributes: { [key in string]: string }, };
