// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LookupCandidate } from "./LookupCandidate";

/**
 * Result of a bibliography metadata lookup, discriminated for user-facing messages.
 */
export type BibliographyLookupOutcome = { "kind": "found", biblatex: string, } | { "kind": "disabled" } | { "kind": "server_unavailable" } | { "kind": "not_an_identifier" } | { "kind": "not_found" } | { "kind": "ambiguous", candidates: Array<LookupCandidate>, session: string, url: string, } | { "kind": "failed", message: string, };
