// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-phase breakdown of the open → first-paint bootstrap.
 */
export type BootstrapPhaseTimings = { 
/**
 * IPC round-trip for loading template package files (e.g. versatile-apa).
 */
templatePackageLoadMs?: number | null, 
/**
 * IPC round-trip for loading dependency package files (e.g. mitex).
 */
dependencyPackageLoadMs?: number | null, 
/**
 * `documentAstForCompile` AST transform duration.
 */
astTransformMs?: number | null, 
/**
 * Worker round-trip for `CompilerClient.bootstrap` (VFS write + sync + compile).
 */
workerBootstrapMs?: number | null, };
