// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompilationJobKind } from "./CompilationJobKind";
import type { CompilationPriority } from "./CompilationPriority";

export type CompilationJob = { job_id: bigint, kind: CompilationJobKind, priority: CompilationPriority, source_revision: bigint, };
