// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompilationStatus } from "./CompilationStatus";
import type { DocumentOutline } from "./DocumentOutline";
import type { DocumentResources } from "./DocumentResources";
import type { PreviewPageFile } from "./PreviewPageFile";

export type CompilationResult = { source_revision: number, status: CompilationStatus, preview_pages: Array<PreviewPageFile> | null, export_path: string | null, diagnostics: Array<string>, outline: DocumentOutline | null, resources: DocumentResources | null, };
