// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExportFormat } from "./ExportFormat";

export type CompilationJobKind = { "type": "previewSvg" } | { "type": "export", format: ExportFormat, };
