// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompilationResult } from "./CompilationResult";

export type CompilationQueueSnapshot = { latest_source_revision: bigint, active_job_id: bigint | null, queued_preview_job_id: bigint | null, queued_export_count: number, last_result: CompilationResult | null, };
