// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CompilationJobKind } from "./CompilationJobKind";
import type { CompilationStatus } from "./CompilationStatus";
import type { PreviewPageFile } from "./PreviewPageFile";

export type CompilationResult = { job_id: bigint, kind: CompilationJobKind, source_revision: bigint, status: CompilationStatus, svgs: Array<string> | null, preview_pages: Array<PreviewPageFile> | null, export_path: string | null, diagnostics: Array<string>, };
