// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContextDescriptor = { name: string, description_key: string, attribute_keys: Array<string>, };
