// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentElement } from "./DocumentElement";

export type ContentSection = { id: string, is_optional: boolean, elements: Array<DocumentElement>, };
