// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Author } from "./Author";

export type CoverPageSection = { id: string, is_optional: boolean, authors: Array<Author>, affiliations: Array<string>, abstract_text: string, course: string | null, instructor: string | null, due_date: string | null, author_note: string | null, };
