// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamSpec } from "./ParamSpec";

export type CustomElementSpec = { kind: string, label: string, description: string | null, function: string, fields: Array<ParamSpec>, };
