// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Package } from "./Package";

export type DependencyManifest = { packages: Array<Package>, };
