// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Diagram = { id: string, mermaid_source: string, asset_id: string | null, caption: string, placement: string, extra_fields: Record<string, any>, };
