// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Equation } from "./Equation";
import type { Figure } from "./Figure";
import type { Heading } from "./Heading";
import type { Paragraph } from "./Paragraph";
import type { Table } from "./Table";

export type DocumentElement = { "type": "Heading" } & Heading | { "type": "Paragraph" } & Paragraph | { "type": "Table" } & Table | { "type": "Equation" } & Equation | { "type": "Figure" } & Figure;
