// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSourceLayout } from "./ProjectSourceLayout";
import type { SourceMapEntry } from "./SourceMapEntry";

export type DocumentSessionStatus = { sourceRevision: bigint, layout: ProjectSourceLayout, sourceMap: Array<SourceMapEntry>, dirtySectionIds: Array<string>, dirtyElementIds: Array<string>, fragmentCount: number, };
