// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomElement } from "./CustomElement";
import type { Diagram } from "./Diagram";
import type { Enumeration } from "./Enumeration";
import type { Equation } from "./Equation";
import type { Figure } from "./Figure";
import type { Heading } from "./Heading";
import type { List } from "./List";
import type { Paragraph } from "./Paragraph";
import type { Quote } from "./Quote";
import type { Table } from "./Table";

export type DocumentElement = { "type": "Heading" } & Heading | { "type": "Paragraph" } & Paragraph | { "type": "Quote" } & Quote | { "type": "List" } & List | { "type": "Enumeration" } & Enumeration | { "type": "Table" } & Table | { "type": "Equation" } & Equation | { "type": "Figure" } & Figure | { "type": "Diagram" } & Diagram | { "type": "Custom" } & CustomElement;
