// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContentSection } from "./ContentSection";
import type { CoverPageSection } from "./CoverPageSection";

export type DocumentSection = { "type": "Content" } & ContentSection | { "type": "CoverPage" } & CoverPageSection;
