// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetEntry } from "./AssetEntry";
import type { DependencyManifest } from "./DependencyManifest";
import type { DocumentSection } from "./DocumentSection";
import type { ProjectMetadata } from "./ProjectMetadata";
import type { ReferenceEntry } from "./ReferenceEntry";

export type DocumentAST = { version: string, metadata: ProjectMetadata, dependencies: DependencyManifest, references: Array<ReferenceEntry>, assets: Array<AssetEntry>, sections: Array<DocumentSection>, };
