// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OutlineEntry } from "./OutlineEntry";

/**
 * Ordered list of headings extracted from a compiled `PagedDocument`.
 */
export type DocumentOutline = { entries: Array<OutlineEntry>, };
