// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentAST } from "./DocumentAST";

export type DocumentEvent = { "type": "snapshotSynced", ast: DocumentAST, };
