// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtraFieldSpec } from "./ExtraFieldSpec";

export type ElementOverrideSpec = { function: string | null, wrapper: string | null, extra_fields: Array<ExtraFieldSpec>, };
