// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementOverrideSpec } from "./ElementOverrideSpec";

export type ElementOverrides = { figure: ElementOverrideSpec | null, table: ElementOverrideSpec | null, };
