// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ListItem } from "./ListItem";

export type Enumeration = { id: string, items: Array<ListItem>, };
