// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EquationSyntax } from "./EquationSyntax";

export type Equation = { id: string, latex_source: string, is_block: boolean, syntax: EquationSyntax, };
