// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Single cross-cutting error type for Érgo.
 *
 * Variants carry the structured fields each failure category actually has, so
 * callers (and, via ts-rs, the frontend) can discriminate on `kind` instead of
 * substring-matching a free-form string. The `Display` text is stable — tests
 * and the frontend rely on it — so each `#[error(...)]` attribute is part of
 * the contract.
 *
 * `Operation` is the generic fallback for host-side IO/serde/zip failures that
 * don't deserve their own variant; its `message` is the underlying error text.
 */
export type ErgoError = { "kind": "elementType", element_id: string, expected: string, } | { "kind": "invalidPath", path: string, } | { "kind": "invalidArrayIndex", index: string, } | { "kind": "pathNotFound", path: string, } | { "kind": "notArray", path: string, } | { "kind": "notContainer", path: string, } | { "kind": "emptyPath" } | { "kind": "vfsNotFound", path: string, } | { "kind": "invalidPatchRange" } | { "kind": "compile", diagnostics: string, } | { "kind": "archive", message: string, } | { "kind": "documentStateRequired" } | { "kind": "operation", message: string, };
