// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FieldTextSegment = { sourceByteStart: number, sourceByteEnd: number, fieldUtf16Start: number, fieldUtf16End: number, };
