// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentElement } from "./DocumentElement";

export type Figure = { id: string, asset_id: string | null, content: DocumentElement, caption: string, placement: string, };
