// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldSourceMapEntry } from "./FieldSourceMapEntry";
import type { SourceMapEntry } from "./SourceMapEntry";

export type GeneratedFragment = { elementId: string, sectionId: string, kind: string, source: string, sourceHash: bigint, dependencies: Array<string>, sourceMapRanges: Array<SourceMapEntry>, fieldSourceMapRanges: Array<FieldSourceMapEntry>, };
