// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of `save_global_settings`. The settings file is always written; a failure
 * to reconcile the Zotero translation-server container is reported here instead of
 * failing the save, so the user's preference stands and the UI can surface it.
 */
export type GlobalSettingsSaveReport = { translation_server_error: string | null, };
