// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EquationSyntax } from "./EquationSyntax";
import type { WorkspaceColumnWidths } from "./WorkspaceColumnWidths";

export type GlobalSettings = { default_font: string | null, default_font_size: number | null, theme_mode: string | null, locale: string | null, recent_projects: Array<string>, history_limit: number | null, autosave_enabled: boolean | null, autosave_interval_ms: number | null, autosave_on_window_blur: boolean | null, autosave_on_app_close: boolean | null, autosave_on_project_close: boolean | null, 
/**
 * Syntax applied to newly inserted equations.
 */
default_equation_syntax: EquationSyntax | null, 
/**
 * Runs the Zotero translation server in a fixed-name Docker container on localhost.
 */
zotero_translation_server_enabled: boolean | null, 
/**
 * Base URL of a translation server the user runs themselves. When set, lookups
 * target it and Érgo manages no Docker container.
 */
zotero_translation_server_url: string | null, 
/**
 * Scale factor applied to preview page rasterization while the user is typing.
 * Full resolution (1.0) is used after an idle window.
 */
preview_draft_render_factor: number | null, 
/**
 * Fraction of the viewport rasterized beyond the visible edges of each preview
 * page (advanced). `0.0` rasterizes exactly what is on screen; a positive value
 * pre-renders a margin so scrolling reveals content with less delay.
 */
preview_render_overscan_factor: number | null, 
/**
 * Milliseconds to wait before re-rasterizing preview canvases after zoom,
 * scroll sharpening, or sidebar resize. A short debounce keeps gestures
 * smooth; zero re-rasterizes on every notification.
 */
preview_rasterization_debounce_ms: number | null, 
/**
 * Milliseconds to wait before re-rasterizing when scrolling or zooming out
 * reveals area the current bitmap no longer covers. Zero repaints
 * immediately; a positive value reduces work during fast scroll.
 */
preview_reveal_debounce_ms: number | null, 
/**
 * Milliseconds to wait before resolving the editor caret's position in the
 * preview (forward sync). Zero resolves on every caret move; a positive
 * value coalesces bursts while typing.
 */
preview_forward_sync_debounce_ms: number | null, 
/**
 * Milliseconds a draft (reduced-resolution) preview render waits while idle
 * before being promoted to full resolution. Only applies when the draft
 * render factor is below 1.
 */
preview_draft_promote_ms: number | null, 
/**
 * Draw a forward-sync caret cue at every visible place the focused source
 * renders (advanced), not just the one nearest the viewport — useful for
 * content repeated across pages such as a title in the running head.
 */
preview_multi_caret: boolean | null, 
/**
 * Last workspace column layout; `None` until the user resizes a column.
 */
workspace_columns: WorkspaceColumnWidths | null, };
