// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyBindingPreference } from "./KeyBindingPreference";

export type GlobalSettings = { default_font: string | null, default_font_size: number | null, theme_mode: string | null, locale: string | null, recent_projects: Array<string>, keymap_profile: string | null, keymap_overrides: Array<KeyBindingPreference>, preview_debounce_ms: number | null, history_limit: number | null, };
