// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EquationSyntax } from "./EquationSyntax";
import type { KeyBindingPreference } from "./KeyBindingPreference";

export type GlobalSettings = { default_font: string | null, default_font_size: number | null, theme_mode: string | null, locale: string | null, recent_projects: Array<string>, keymap_profile: string | null, keymap_overrides: Array<KeyBindingPreference>, history_limit: number | null, autosave_enabled: boolean | null, autosave_interval_ms: number | null, autosave_on_window_blur: boolean | null, autosave_on_app_close: boolean | null, autosave_on_project_close: boolean | null, 
/**
 * Syntax applied to newly inserted equations.
 */
default_equation_syntax: EquationSyntax | null, };
