// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssetEntry } from "./AssetEntry";

export type ImportResourceResult = { asset: AssetEntry, bytes: Array<number>, };
