// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InputType = "string" | "integer" | "float" | "boolean" | "array" | "object" | "reference" | "content" | "content_blocks" | "simple_list";
