// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyBindingPreference } from "./KeyBindingPreference";

export type KeymapProfileRecord = { id: string, name: string, overrides: Array<KeyBindingPreference>, };
