// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActionId } from "./ActionId";
import type { KeyStroke } from "./KeyStroke";

export type KeymapConflict = { action_id: ActionId, conflicting_action_id: ActionId, context: string, sequence: Array<KeyStroke>, };
