// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyModifier } from "./KeyModifier";

export type KeyStroke = { key: string, modifiers: Array<KeyModifier>, };
