// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentAST } from "./DocumentAST";
import type { ProjectFile } from "./ProjectFile";

export type OpenProjectResult = { ast: DocumentAST, files: Array<ProjectFile>, };
