// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single heading entry in the compiled document outline.
 */
export type OutlineEntry = { 
/**
 * Heading level (1 = `=`, 2 = `==`, etc.)
 */
level: number, 
/**
 * Plain text content of the heading.
 */
text: string, 
/**
 * 1-based page number where this heading appears.
 */
page: number, };
