// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PackageDependency } from "./PackageDependency";

export type PackageSpec = { name: string, version: string, dependencies: Array<PackageDependency>, };
