// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamType } from "./ParamType";

export type ParamSpec = { key: string, type: ParamType, source: string | null, label: string | null, default: unknown, required: boolean, };
