// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which editing surface the typing phase targets.
 */
export type PerfTypingTarget = "body" | "formTitle";
