// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Wall-clock duration of a one-shot measurement (startup, project load, etc.).
 * No per-keystroke breakdown — just the total and a label for context.
 */
export type PerfOneShotTiming = { 
/**
 * Human-readable label, e.g. "appStart", "projectLoad".
 */
label: string, 
/**
 * Total elapsed milliseconds.
 */
elapsedMs: number, };
