// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PerfTypingTarget } from "./PerfTypingTarget";

export type PerfHarnessConfig = { enabled: boolean, projectPath: string | null, reportPath: string | null, keystrokeCount: number, warmupKeystrokes: number, keystrokeIntervalMs: number, 
/**
 * Manual preview zoom to apply before typing. High zoom exercises the
 * raster-bound regime where visible-band rasterization matters most. `None`
 * leaves the preview at its default zoom.
 */
zoom: number | null, 
/**
 * Which editing surface to drive during the typing phase.
 */
typingTarget: PerfTypingTarget, };
