// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PerfTelemetrySample = { keystrokeIndex: number, 
/**
 * Earliest input (ProseMirror transaction) → AST event queued. Zero for
 * non-ProseMirror targets that bypass the input pipeline.
 */
inputToCommitMs: number, totalLatencyMs: number, queuedToSyncMs: number, workerSyncMs: number, compileMs: number, svgRenderMs: number, scheduleMs: number, deferMs: number, commitMs: number, reactCommitMs: number, paintMs: number, workerRenderMs: number, domWriteMs: number, rasterMs: number, };
