// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PerfHarnessConfig = { enabled: boolean, projectPath: string | null, reportPath: string | null, keystrokeCount: number, warmupKeystrokes: number, keystrokeIntervalMs: bigint, };
