// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PerfHarnessConfig } from "./PerfHarnessConfig";
import type { PerfReportSummary } from "./PerfReportSummary";
import type { PerfTelemetrySample } from "./PerfTelemetrySample";

export type PerfHarnessReport = { config: PerfHarnessConfig, samples: Array<PerfTelemetrySample>, summary: PerfReportSummary, };
