// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PerfReportSummary = { sampleCount: number, 
/**
 * Mean input→commit (the synchronous input-pipeline prefix). Zero for
 * targets that bypass ProseMirror.
 */
inputToCommitMeanMs: number, totalLatencyMeanMs: number, totalLatencyP50Ms: number, totalLatencyP90Ms: number, compileMeanMs: number, compileP50Ms: number, compileP90Ms: number, svgRenderMeanMs: number, scheduleMeanMs: number, 
/**
 * Mean of the first post-warmup keystroke across runs (when available).
 * First-keystroke latency is typically much higher than steady state
 * because of JIT warmup, font cache misses, and lazy module init.
 */
firstKeystrokeMs: number | null, };
