// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PerfReportSummary = { sampleCount: number, totalLatencyMeanMs: number, totalLatencyP50Ms: number, totalLatencyP90Ms: number, compileMeanMs: number, compileP50Ms: number, compileP90Ms: number, svgRenderMeanMs: number, scheduleMeanMs: number, };
