// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BootstrapPhaseTimings } from "./BootstrapPhaseTimings";
import type { PerfHarnessConfig } from "./PerfHarnessConfig";
import type { PerfOneShotTiming } from "./PerfOneShotTiming";
import type { PerfReportSummary } from "./PerfReportSummary";
import type { PerfTelemetrySample } from "./PerfTelemetrySample";

export type PerfHarnessReport = { config: PerfHarnessConfig, samples: Array<PerfTelemetrySample>, summary: PerfReportSummary, 
/**
 * One-shot timings collected before the typing loop:
 * `appStart` (module eval → first paint) and `projectLoad` (openProject →
 * first preview paint). Empty when not measured.
 */
oneShotTimings: Array<PerfOneShotTiming>, 
/**
 * Bootstrap-phase breakdown (open → first paint), when captured:
 * template-package IPC, dependency-package IPC, AST transform, worker
 * bootstrap compile. Empty when not measured.
 */
bootstrapPhases: BootstrapPhaseTimings, };
