// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreviewPageFile = { page_number: number, path: string, changed: boolean, width_pt: number | null, height_pt: number | null, content: string | null, };
