// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreviewFocusTarget = { elementId: string, fieldId: string | null, caretUtf16Offset: number | null, anchorPageNumber: number | null, sourceRevision: number, };
