// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PreviewElementPosition = { elementId: string | null, pageNumber: number, xPt: number, yPt: number, sourceRevision: bigint, };
