// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewElementPosition } from "./PreviewElementPosition";

export type PreviewJumpResult = { "status": "element", elementId: string, sourceRevision: bigint, } | { "status": "position", position: PreviewElementPosition, sourceRevision: bigint, } | { "status": "noMatch", sourceRevision: bigint | null, reason: string, } | { "status": "unavailable", sourceRevision: bigint | null, reason: string, };
