// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewPageMetrics } from "./PreviewPageMetrics";

export type PreviewSyncStatus = { sourceRevision: bigint | null, pages: Array<PreviewPageMetrics>, };
