// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewElementPosition } from "./PreviewElementPosition";
import type { PreviewFocusTarget } from "./PreviewFocusTarget";

export type PreviewJumpResult = { "status": "field", target: PreviewFocusTarget, sourceRevision: number, } | { "status": "element", elementId: string, sourceRevision: number, } | { "status": "position", position: PreviewElementPosition, sourceRevision: number, } | { "status": "noMatch", sourceRevision: number | null, reason: string, } | { "status": "unavailable", sourceRevision: number | null, reason: string, };
