// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GlobalSettings } from "./GlobalSettings";
import type { ProjectSettings } from "./ProjectSettings";

export type ProjectMetadata = { template_id: string, title: string, project_settings: ProjectSettings, local_overrides: GlobalSettings, };
