// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FontAvailability } from "./FontAvailability";

export type ProjectFontAvailability = { textFont: FontAvailability, mathFont: FontAvailability, rawFont: FontAvailability, };
