// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateOverride } from "./TemplateOverride";

export type ProjectSettings = { paper_size: string | null, language: string | null, text_font: string | null, math_font: string | null, raw_font: string | null, font_size: number | null, table_stroke_width: number | null, template_overrides: Array<TemplateOverride>, };
