// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectSourceLayout = { mainPath: string, sectionPaths: Array<string>, referencesPath: string, sourceMapPath: string, documentStatePath: string, projectSettingsPath: string, templatePath: string, };
