// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RichText } from "./RichText";

export type Quote = { id: string, content: Array<RichText>, };
