// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Template-authored rule for when quotations render as block vs inline in the editor
 * and in generated Typst (`#quote(block: …)`).
 *
 * Serialized as either a word threshold (e.g. `40`), or the strings `"block"` / `"inline"`.
 */
export type QuotePolicySpec = number | string;
