// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RichText } from "./RichText";

export type Quote = { id: string, content: Array<RichText>, 
/**
 * Parenthetical or narrative attribution text (APA-style). Mutually exclusive
 * with `attribution_reference_id`.
 */
attribution_text: string | null, 
/**
 * Bibliography entry cited as the quote attribution. Mutually exclusive with
 * `attribution_text`.
 */
attribution_reference_id: string | null, };
