// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourcePreviewStatus } from "./ResourcePreviewStatus";

export type ResourcePreview = { status: ResourcePreviewStatus, path: string | null, 
/**
 * 1-based page index in the compiled `resources.typ` document (canvas preview).
 */
page_number: number | null, content: string | null, diagnostic: string | null, };
