// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ResourcePreviewPolicySpec = { 
/**
 * Deprecated. Per-kind preview page sizing is defined by
 * `ResourceKind::preview_page_size()` (`ResourcePreviewPageSize`).
 */
width_pt: number | null, margin_pt: number | null, wrapper: string | null, };
