// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceKind } from "./ResourceKind";
import type { ResourcePreview } from "./ResourcePreview";

export type ResourceEntry = { id: string, kind: ResourceKind, label: string, subtitle: string | null, reference_token: string, source_element_id: string | null, asset_id: string | null, preview: ResourcePreview, };
