// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceEntry } from "./ResourceEntry";
import type { ResourceKind } from "./ResourceKind";

export type ResourceGroup = { kind: ResourceKind, label: string, entries: Array<ResourceEntry>, };
