// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EquationSyntax } from "./EquationSyntax";

export type RichText = { text: string, bold: boolean | null, italic: boolean | null, underline: boolean | null, kind: string | null, reference_id: string | null, equation_source: string | null, equation_syntax: EquationSyntax, };
