// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EquationSyntax } from "./EquationSyntax";

export type RichText = { text: string, bold: boolean | null, italic: boolean | null, underline: boolean | null, kind: string | null, reference_id: string | null, equation_source: string | null, equation_syntax: EquationSyntax, 
/**
 * Quote attribution text for inline quote spans (`kind == "quote"`).
 */
quote_attribution_text: string | null, 
/**
 * Bibliography entry for inline quote attribution. Mutually exclusive with
 * `quote_attribution_text`.
 */
quote_attribution_reference_id: string | null, };
