// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamSpec } from "./ParamSpec";
import type { SectionKind } from "./SectionKind";

export type SectionSpec = { id: string, kind: SectionKind, label: string | null, function: string | null, params: Array<ParamSpec>, variants: Array<string> | null, source: string | null, file: string | null, title: string | null, show_rule: string | null, editable: boolean | null, pagebreak_before: boolean, };
