// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ParamSpec } from "./ParamSpec";

export type ShowRuleSpec = { function: string, params: Array<ParamSpec>, };
