// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SourceMapEntry = { elementId: string, sectionId: string, filePath: string, start: number, end: number, byteStart: number, byteEnd: number, label: string, page: number | null, };
