// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RichText } from "./RichText";

export type TableCell = { content: Array<RichText>, row_span: number | null, col_span: number | null, };
