// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DocumentElement } from "./DocumentElement";

export type TableCell = { elements: Array<DocumentElement>, row_span: number | null, col_span: number | null, };
