// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TableCell } from "./TableCell";

export type Table = { id: string, rows: number, cols: number, cells: Array<Array<TableCell>>, column_sizes: Array<string>, };
