// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TableCell = { content: string, row_span: number | null, col_span: number | null, };
