// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TemplateOptionChoice } from "./TemplateOptionChoice";
import type { TemplateOptionKind } from "./TemplateOptionKind";

export type TemplateOptionSpec = { id: string, label: string, description: string | null, kind: TemplateOptionKind, default: unknown, choices: Array<TemplateOptionChoice>, };
