// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditorConfig } from "./EditorConfig";
import type { TemplateMetadata } from "./TemplateMetadata";
import type { TypstConfig } from "./TypstConfig";

export type TemplateSpec = { metadata: TemplateMetadata, typst: TypstConfig, editor: EditorConfig, messages: { [key in string]: { [key in string]: string } }, };
