// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomElementSpec } from "./CustomElementSpec";
import type { DefaultsSpec } from "./DefaultsSpec";
import type { ElementOverrides } from "./ElementOverrides";
import type { InputGroupSpec } from "./InputGroupSpec";
import type { InputSchema } from "./InputSchema";
import type { PackageSpec } from "./PackageSpec";
import type { ResourcePolicySpec } from "./ResourcePolicySpec";
import type { SectionSpec } from "./SectionSpec";
import type { ShowRuleSpec } from "./ShowRuleSpec";
import type { TemplateIdentity } from "./TemplateIdentity";
import type { TemplateVariantSpec } from "./TemplateVariantSpec";

export type TemplateSpec = { template: TemplateIdentity, package: PackageSpec, variants: Array<TemplateVariantSpec>, show_rule: ShowRuleSpec | null, inputs: Array<InputSchema>, groups: Array<InputGroupSpec>, custom_elements: Array<CustomElementSpec>, sections: Array<SectionSpec>, element_overrides: ElementOverrides | null, resource_policy: ResourcePolicySpec | null, defaults: DefaultsSpec | null, };
