// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type TranslationServerStatus = { 
/**
 * Docker CLI reachable. Always true when a custom server URL is configured.
 */
docker_available: boolean, 
/**
 * Managed container running; for a custom server URL, same as `ready`.
 */
running: boolean, 
/**
 * The server answered an HTTP probe.
 */
ready: boolean, 
/**
 * Managed container running but the server does not answer yet.
 */
starting: boolean, enabled: boolean, };
