// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ElementOverrides } from "./ElementOverrides";
import type { PackageSpec } from "./PackageSpec";
import type { ResourcePolicySpec } from "./ResourcePolicySpec";
import type { SectionSpec } from "./SectionSpec";
import type { ShowRuleSpec } from "./ShowRuleSpec";
import type { TemplateOverride } from "./TemplateOverride";

export type TypstConfig = { package: PackageSpec, show_rule: ShowRuleSpec | null, sections: Array<SectionSpec>, element_overrides: ElementOverrides | null, resource_policy: ResourcePolicySpec | null, default_template_overrides: Array<TemplateOverride>, };
