// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted widths of the resizable workspace columns (sidebar and editor); the
 * preview takes the remaining width.
 */
export type WorkspaceColumnWidths = { sidebar: number, editor: number, };
