// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceGroup } from "./ResourceGroup";

export type DocumentResources = { groups: Array<ResourceGroup>, revision: bigint, };
