// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldTextSegment } from "./FieldTextSegment";

export type FieldSourceMapEntry = { elementId: string, sectionId: string, fieldId: string, filePath: string, byteStart: number, byteEnd: number, segments: Array<FieldTextSegment>, fallbackCaretUtf16Offset: number | null, };
