// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyBindingPreference } from "./KeyBindingPreference";

export type KeymapSettings = { keymap_profile: string | null, keymap_bindings: Array<KeyBindingPreference>, keymap_overrides: Array<KeyBindingPreference>, };
