// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ParamType = "content" | "string" | "length" | "boolean" | "integer" | "float" | "string_array" | "content_array" | "dictionary" | "author_list" | "affiliation_map";
