// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewCaretCue } from "./PreviewCaretCue";

export type PreviewElementPosition = { elementId: string | null, fieldId: string | null, caretUtf16Offset: number | null, pageNumber: number, xPt: number, yPt: number, caretCue: PreviewCaretCue | null, sourceRevision: number, };
