// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PreviewElementPosition } from "./PreviewElementPosition";

export type PreviewElementPositionsResult = { "status": "matched", positions: Array<PreviewElementPosition>, sourceRevision: number, } | { "status": "noMatch", sourceRevision: number | null, reason: string, } | { "status": "unavailable", sourceRevision: number | null, reason: string, };
