// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PastedImagePolicySpec } from "./PastedImagePolicySpec";
import type { ResourcePreviewPolicySpec } from "./ResourcePreviewPolicySpec";

export type ResourcePolicySpec = { preview: ResourcePreviewPolicySpec | null, pasted_image: PastedImagePolicySpec | null, };
