// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourcePreviewStatus } from "./ResourcePreviewStatus";

export type ResourcePreview = { status: ResourcePreviewStatus, path: string | null, diagnostic: string | null, };
