use crate::action_types::ActionDescriptor;
use crate::ast::ActionId;

pub fn action_catalog() -> Vec<ActionDescriptor> {
    vec![
        descriptor(
            ActionId::WorkspaceNewProject,
            "action_workspace_new_project",
            "workspace",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::WorkspaceOpenProject,
            "action_workspace_open_project",
            "workspace",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::WorkspaceOpenRecentProject,
            "action_workspace_open_recent_project",
            "workspace",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::WorkspaceSaveProject,
            "action_workspace_save_project",
            "workspace",
            "workspace && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::WorkspaceCloseProject,
            "action_workspace_close_project",
            "workspace",
            "workspace",
            true,
            true,
        ),
        descriptor(
            ActionId::WorkspaceExportSvg,
            "action_workspace_export_svg",
            "workspace",
            "workspace && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditUndo,
            "action_edit_undo",
            "edit",
            "workspace && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditRedo,
            "action_edit_redo",
            "edit",
            "workspace && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorDeleteElement,
            "action_editor_delete_element",
            "editor",
            "element && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorInsertParagraph,
            "action_editor_insert_paragraph",
            "editor",
            "editor && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorInsertHeading,
            "action_editor_insert_heading",
            "editor",
            "editor && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorInsertTable,
            "action_editor_insert_table",
            "editor",
            "editor && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorInsertFigure,
            "action_editor_insert_figure",
            "editor",
            "editor && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorInsertEquation,
            "action_editor_insert_equation",
            "editor",
            "editor && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorInsertBlockEquation,
            "action_editor_insert_block_equation",
            "editor",
            "editor && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorInsertInlineEquation,
            "action_editor_insert_inline_equation",
            "editor",
            "editor && input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorInsertQuote,
            "action_editor_insert_quote",
            "editor",
            "editor && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorInsertDiagram,
            "action_editor_insert_diagram",
            "editor",
            "editor && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorInsertList,
            "action_editor_insert_list",
            "editor",
            "editor && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorInsertEnumeration,
            "action_editor_insert_enumeration",
            "editor",
            "editor && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorInsertReference,
            "action_editor_insert_reference",
            "editor",
            "editor && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorBold,
            "action_editor_bold",
            "editor",
            "input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorItalic,
            "action_editor_italic",
            "editor",
            "input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorUnderline,
            "action_editor_underline",
            "editor",
            "input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorAddAuthor,
            "action_editor_add_author",
            "editor",
            "coverPage",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorRemoveAuthor,
            "action_editor_remove_author",
            "editor",
            "coverPage",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorAddTableRow,
            "action_editor_add_table_row",
            "editor",
            "element && element.kind == \"Table\"",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorAddTableColumn,
            "action_editor_add_table_column",
            "editor",
            "element && element.kind == \"Table\"",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorRemoveTableRow,
            "action_editor_remove_table_row",
            "editor",
            "element && element.kind == \"Table\"",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorRemoveTableColumn,
            "action_editor_remove_table_column",
            "editor",
            "element && element.kind == \"Table\"",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorConvertToParagraph,
            "action_editor_convert_to_paragraph",
            "editor",
            "element && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorConvertToHeading,
            "action_editor_convert_to_heading",
            "editor",
            "element && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorConvertToTable,
            "action_editor_convert_to_table",
            "editor",
            "element && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorConvertToEquation,
            "action_editor_convert_to_equation",
            "editor",
            "element && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorConvertToFigure,
            "action_editor_convert_to_figure",
            "editor",
            "element && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::BibliographyCreateEntry,
            "action_bibliography_create_entry",
            "bibliography",
            "bibliography",
            true,
            true,
        ),
        descriptor(
            ActionId::BibliographyOpenEntry,
            "action_bibliography_open_entry",
            "bibliography",
            "bibliography",
            false,
            true,
        ),
        descriptor(
            ActionId::BibliographySaveEntry,
            "action_bibliography_save_entry",
            "bibliography",
            "bibliography",
            false,
            true,
        ),
        descriptor(
            ActionId::BibliographyRemoveEntry,
            "action_bibliography_remove_entry",
            "bibliography",
            "bibliography",
            false,
            true,
        ),
        descriptor(
            ActionId::BibliographyCancelEdit,
            "action_bibliography_cancel_edit",
            "bibliography",
            "bibliography",
            false,
            true,
        ),
        descriptor(
            ActionId::ResourcesCreate,
            "action_resources_create",
            "resources",
            "resources",
            true,
            true,
        ),
        descriptor(
            ActionId::ResourcesOpen,
            "action_resources_open",
            "resources",
            "resources",
            false,
            true,
        ),
        descriptor(
            ActionId::ResourcesEdit,
            "action_resources_edit",
            "resources",
            "resources",
            false,
            true,
        ),
        descriptor(
            ActionId::ResourcesSave,
            "action_resources_save",
            "resources",
            "resources",
            false,
            true,
        ),
        descriptor(
            ActionId::ResourcesRemove,
            "action_resources_remove",
            "resources",
            "resources",
            false,
            true,
        ),
        descriptor(
            ActionId::ResourcesInsertReference,
            "action_resources_insert_reference",
            "resources",
            "resources",
            true,
            true,
        ),
        descriptor(
            ActionId::ViewOpenCommandPalette,
            "action_view_open_command_palette",
            "view",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::ViewZoomIn,
            "action_view_zoom_in",
            "view",
            "preview",
            true,
            true,
        ),
        descriptor(
            ActionId::ViewZoomOut,
            "action_view_zoom_out",
            "view",
            "preview",
            true,
            true,
        ),
        descriptor(
            ActionId::ThemeUseSystem,
            "action_theme_use_system",
            "settings",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::ThemeUseLight,
            "action_theme_use_light",
            "settings",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::ThemeUseDark,
            "action_theme_use_dark",
            "settings",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::SettingsOpenGlobal,
            "action_settings_open_global",
            "settings",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::SettingsOpenProject,
            "action_settings_open_project",
            "settings",
            "workspace",
            true,
            true,
        ),
        descriptor(
            ActionId::SettingsOpenKeymap,
            "action_settings_open_keymap",
            "settings",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::SettingsClose,
            "action_settings_close",
            "settings",
            "dialog",
            false,
            false,
        ),
        descriptor(
            ActionId::HelpOpenDocumentation,
            "action_help_open_documentation",
            "help",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::HelpOpenAbout,
            "action_help_open_about",
            "help",
            "app",
            true,
            false,
        ),
    ]
}

fn descriptor(
    id: ActionId,
    label_key: &str,
    category: &str,
    default_context: &str,
    allows_keybinding: bool,
    requires_project: bool,
) -> ActionDescriptor {
    ActionDescriptor {
        id,
        label_key: label_key.to_string(),
        category: category.to_string(),
        default_context: default_context.to_string(),
        allows_keybinding,
        requires_project,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn catalog_contains_bibliography_and_resource_actions() {
        let ids = action_catalog()
            .into_iter()
            .map(|descriptor| descriptor.id.as_str())
            .collect::<Vec<_>>();

        assert!(ids.contains(&"bibliography::CreateEntry"));
        assert!(ids.contains(&"bibliography::OpenEntry"));
        assert!(ids.contains(&"bibliography::SaveEntry"));
        assert!(ids.contains(&"bibliography::RemoveEntry"));
        assert!(ids.contains(&"bibliography::CancelEdit"));
        assert!(ids.contains(&"resources::Create"));
        assert!(ids.contains(&"resources::Open"));
        assert!(ids.contains(&"resources::Edit"));
        assert!(ids.contains(&"resources::Save"));
        assert!(ids.contains(&"resources::Remove"));
        assert!(ids.contains(&"resources::InsertReference"));
    }
}
