use crate::action_types::ActionDescriptor;
use crate::ast::ActionId;

pub fn action_catalog() -> Vec<ActionDescriptor> {
    vec![
        descriptor(
            ActionId::WorkspaceNewProject,
            "action_workspace_new_project",
            "workspace",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::WorkspaceOpenProject,
            "action_workspace_open_project",
            "workspace",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::WorkspaceOpenRecentProject,
            "action_workspace_open_recent_project",
            "workspace",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::WorkspaceSaveProject,
            "action_workspace_save_project",
            "workspace",
            "workspace && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::WorkspaceCloseProject,
            "action_workspace_close_project",
            "workspace",
            "workspace",
            true,
            true,
        ),
        descriptor(
            ActionId::WorkspaceExportSvg,
            "action_workspace_export_svg",
            "workspace",
            "workspace && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditUndo,
            "action_edit_undo",
            "edit",
            "workspace && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditRedo,
            "action_edit_redo",
            "edit",
            "workspace && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorDeleteElement,
            "action_editor_delete_element",
            "editor",
            "element && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorInsertParagraph,
            "action_editor_insert_paragraph",
            "editor",
            "editor && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorInsertHeading,
            "action_editor_insert_heading",
            "editor",
            "editor && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorInsertTable,
            "action_editor_insert_table",
            "editor",
            "editor && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorInsertFigure,
            "action_editor_insert_figure",
            "editor",
            "editor && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorInsertEquation,
            "action_editor_insert_equation",
            "editor",
            "editor && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorInsertReference,
            "action_editor_insert_reference",
            "editor",
            "editor && !input",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorAddAuthor,
            "action_editor_add_author",
            "editor",
            "coverPage",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorRemoveAuthor,
            "action_editor_remove_author",
            "editor",
            "coverPage",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorAddTableRow,
            "action_editor_add_table_row",
            "editor",
            "element && element.kind == \"Table\"",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorAddTableColumn,
            "action_editor_add_table_column",
            "editor",
            "element && element.kind == \"Table\"",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorRemoveTableRow,
            "action_editor_remove_table_row",
            "editor",
            "element && element.kind == \"Table\"",
            true,
            true,
        ),
        descriptor(
            ActionId::EditorRemoveTableColumn,
            "action_editor_remove_table_column",
            "editor",
            "element && element.kind == \"Table\"",
            true,
            true,
        ),
        descriptor(
            ActionId::ViewOpenCommandPalette,
            "action_view_open_command_palette",
            "view",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::ViewZoomIn,
            "action_view_zoom_in",
            "view",
            "preview",
            true,
            true,
        ),
        descriptor(
            ActionId::ViewZoomOut,
            "action_view_zoom_out",
            "view",
            "preview",
            true,
            true,
        ),
        descriptor(
            ActionId::ThemeUseSystem,
            "action_theme_use_system",
            "settings",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::ThemeUseLight,
            "action_theme_use_light",
            "settings",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::ThemeUseDark,
            "action_theme_use_dark",
            "settings",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::SettingsOpenGlobal,
            "action_settings_open_global",
            "settings",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::SettingsOpenProject,
            "action_settings_open_project",
            "settings",
            "workspace",
            true,
            true,
        ),
        descriptor(
            ActionId::SettingsOpenKeymap,
            "action_settings_open_keymap",
            "settings",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::SettingsClose,
            "action_settings_close",
            "settings",
            "dialog",
            false,
            false,
        ),
        descriptor(
            ActionId::HelpOpenDocumentation,
            "action_help_open_documentation",
            "help",
            "app",
            true,
            false,
        ),
        descriptor(
            ActionId::HelpOpenAbout,
            "action_help_open_about",
            "help",
            "app",
            true,
            false,
        ),
    ]
}

fn descriptor(
    id: ActionId,
    label_key: &str,
    category: &str,
    default_context: &str,
    allows_keybinding: bool,
    requires_project: bool,
) -> ActionDescriptor {
    ActionDescriptor {
        id,
        label_key: label_key.to_string(),
        category: category.to_string(),
        default_context: default_context.to_string(),
        allows_keybinding,
        requires_project,
    }
}
